/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_joseluispereira;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author j0c3lwiz
 */
public class princi2 extends javax.swing.JFrame {

    /**
     * Creates new form princi2
     */
    public princi2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Crear_mundo = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_codigo_universo = new javax.swing.JTextField();
        bt_crear_universo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf_edad_universo = new javax.swing.JSpinner();
        Crear_Criatura = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_raza = new javax.swing.JTextField();
        tf_region = new javax.swing.JTextField();
        tf_objetos = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        bt_enviar = new javax.swing.JButton();
        tf_anos = new javax.swing.JSpinner();
        tf_criaturasvivs = new javax.swing.JSpinner();
        tf_pesoc = new javax.swing.JSpinner();
        tf_energia = new javax.swing.JSpinner();
        Crear_mundo2 = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_nom_tortuga = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        enviar_mundo = new javax.swing.JButton();
        tf_peso_detotr = new javax.swing.JSpinner();
        popup_agregar_mundo = new javax.swing.JPopupMenu();
        agregar_mundo = new javax.swing.JMenuItem();
        modificar_mundo = new javax.swing.JMenuItem();
        eliminar_mundo = new javax.swing.JMenuItem();
        popup_agregar_Criatura = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_mundo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_criaturas = new javax.swing.JList<>();
        jl_mundoD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_arbol = new javax.swing.JTree();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        c_universo = new javax.swing.JMenuItem();
        c_criatura = new javax.swing.JMenuItem();
        c_mundo = new javax.swing.JMenuItem();

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Codigo del universo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Edad del universo");

        bt_crear_universo.setText("Enviar");
        bt_crear_universo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crear_universoMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Crear Universo");

        tf_edad_universo.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout Crear_mundoLayout = new javax.swing.GroupLayout(Crear_mundo.getContentPane());
        Crear_mundo.getContentPane().setLayout(Crear_mundoLayout);
        Crear_mundoLayout.setHorizontalGroup(
            Crear_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_mundoLayout.createSequentialGroup()
                .addGroup(Crear_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Crear_mundoLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(bt_crear_universo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Crear_mundoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(Crear_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(Crear_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_codigo_universo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_edad_universo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Crear_mundoLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Crear_mundoLayout.setVerticalGroup(
            Crear_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_mundoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel5)
                .addGap(56, 56, 56)
                .addGroup(Crear_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_codigo_universo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(Crear_mundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_edad_universo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(bt_crear_universo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Nombre de la raza");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Numero de Energia");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Numero max de años");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("Nombre de la region");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Cantidad de criaturas vivas");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Lista de objetos magicos (usando \",\")");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Peso de la criatura");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setText("Crear Criatura");

        bt_enviar.setText("Enviar");
        bt_enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_enviarMouseClicked(evt);
            }
        });

        tf_anos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        tf_criaturasvivs.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        tf_pesoc.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        tf_energia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout Crear_CriaturaLayout = new javax.swing.GroupLayout(Crear_Criatura.getContentPane());
        Crear_Criatura.getContentPane().setLayout(Crear_CriaturaLayout);
        Crear_CriaturaLayout.setHorizontalGroup(
            Crear_CriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_CriaturaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(Crear_CriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Crear_CriaturaLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_criaturasvivs, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))
                    .addGroup(Crear_CriaturaLayout.createSequentialGroup()
                        .addGroup(Crear_CriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Crear_CriaturaLayout.createSequentialGroup()
                                .addGroup(Crear_CriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(Crear_CriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(Crear_CriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Crear_CriaturaLayout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(tf_anos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Crear_CriaturaLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(Crear_CriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_raza)
                                            .addComponent(tf_region, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                            .addComponent(tf_energia, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(Crear_CriaturaLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_pesoc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Crear_CriaturaLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_objetos, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(Crear_CriaturaLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel13)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Crear_CriaturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_enviar)
                .addGap(260, 260, 260))
        );
        Crear_CriaturaLayout.setVerticalGroup(
            Crear_CriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_CriaturaLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Crear_CriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Crear_CriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_energia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(Crear_CriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_anos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(Crear_CriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Crear_CriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_criaturasvivs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Crear_CriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_objetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(Crear_CriaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_pesoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(bt_enviar)
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Nombre de la Tortuga");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Peso de la Tortuga");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel16.setText("Crear Mundo");

        enviar_mundo.setText("Enviar");
        enviar_mundo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviar_mundoMouseClicked(evt);
            }
        });

        tf_peso_detotr.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout Crear_mundo2Layout = new javax.swing.GroupLayout(Crear_mundo2.getContentPane());
        Crear_mundo2.getContentPane().setLayout(Crear_mundo2Layout);
        Crear_mundo2Layout.setHorizontalGroup(
            Crear_mundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_mundo2Layout.createSequentialGroup()
                .addGroup(Crear_mundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Crear_mundo2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(Crear_mundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Crear_mundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nom_tortuga, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_peso_detotr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Crear_mundo2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel16))
                    .addGroup(Crear_mundo2Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(enviar_mundo)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        Crear_mundo2Layout.setVerticalGroup(
            Crear_mundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_mundo2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel16)
                .addGap(72, 72, 72)
                .addGroup(Crear_mundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_nom_tortuga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(Crear_mundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_peso_detotr, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(enviar_mundo)
                .addGap(33, 33, 33))
        );

        agregar_mundo.setText("Agregar Mundo");
        agregar_mundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_mundoActionPerformed(evt);
            }
        });
        popup_agregar_mundo.add(agregar_mundo);

        modificar_mundo.setText("Modificar Mundo");
        modificar_mundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_mundoActionPerformed(evt);
            }
        });
        popup_agregar_mundo.add(modificar_mundo);

        eliminar_mundo.setText("Eliminar");
        eliminar_mundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_mundoActionPerformed(evt);
            }
        });
        popup_agregar_mundo.add(eliminar_mundo);

        jMenuItem1.setText("Agregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        popup_agregar_Criatura.add(jMenuItem1);

        jMenuItem2.setText("Modificar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        popup_agregar_Criatura.add(jMenuItem2);

        jMenuItem3.setText("Eliminar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        popup_agregar_Criatura.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_mundo.setModel(new DefaultListModel());
        jl_mundo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_mundoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_mundo);

        jl_criaturas.setModel(new DefaultListModel());
        jl_criaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_criaturasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_criaturas);

        jl_mundoD.setText("Enviar Mundo ");
        jl_mundoD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_mundoDMouseClicked(evt);
            }
        });

        jLabel1.setText("Mundo Disco");

        jLabel2.setText("Criaturas");

        jButton1.setText("Enviar Criaturas");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Universo");
        jt_arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jt_arbol);

        jMenu1.setText("Crear");

        c_universo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        c_universo.setText("Crear Universo");
        c_universo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_universoActionPerformed(evt);
            }
        });
        jMenu1.add(c_universo);

        c_criatura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        c_criatura.setText("Crear Criatura");
        c_criatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_criaturaActionPerformed(evt);
            }
        });
        jMenu1.add(c_criatura);

        c_mundo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        c_mundo.setText("Crear Mundo");
        c_mundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_mundoActionPerformed(evt);
            }
        });
        jMenu1.add(c_mundo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jl_mundoD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_mundoD)
                            .addComponent(jButton1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_universoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_universoActionPerformed
        Crear_mundo.setModal(true);//para solo poder a acceder a una ventana
        Crear_mundo.pack();
        Crear_mundo.setLocationRelativeTo(this);//centra con el frame principal
        Crear_mundo.setVisible(true);
    }//GEN-LAST:event_c_universoActionPerformed

    private void c_criaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_criaturaActionPerformed
        // TODO add your handling code here:
        /*
        Nombre de la raza.
•	Numero de energía.
•	Número máximo de años.
•	Nombre de la región.
•	Cantidad vivas de esa especie.
•	Lista de nombres de objetos mágicos propios de esas criaturas(puede estar vacía).
•	Peso criaturas
         */
        //String raza, int energia, int max_anos, String region, int c_vivas, ArrayList<String> objetos, int peso_criaturas
        Crear_Criatura.setModal(true);//para solo poder a acceder a una ventana
        Crear_Criatura.pack();
        Crear_Criatura.setLocationRelativeTo(this);
        Crear_Criatura.setVisible(true);

    }//GEN-LAST:event_c_criaturaActionPerformed

    private void c_mundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_mundoActionPerformed
        Crear_mundo2.setModal(true);//para solo poder a acceder a una ventana
        Crear_mundo2.pack();
        Crear_mundo2.setLocationRelativeTo(this);//centra con el frame principal
        Crear_mundo2.setVisible(true);
    }//GEN-LAST:event_c_mundoActionPerformed

    private void bt_enviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_enviarMouseClicked
        String sp = tf_objetos.getText();
        String tokens[] = sp.split(",");
         listas = new ArrayList();
        for (int i = 0; i < tokens.length; i++) {
            listas.add(tokens[i]);
        }
        DefaultListModel modeloli = (DefaultListModel) jl_criaturas.getModel();
        modeloli.addElement(new Criaturas(tf_raza.getText(), (Integer) tf_energia.getValue(), (Integer) tf_anos.getValue(), tf_region.getText(), (Integer) tf_criaturasvivs.getValue(), listas, (Integer) tf_pesoc.getValue()));        
        Crear_Criatura.setVisible(false);

    }//GEN-LAST:event_bt_enviarMouseClicked

    private void enviar_mundoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_mundoMouseClicked
        model = (DefaultListModel) jl_mundo.getModel();
        model.addElement(new mundo_disco(tf_nom_tortuga.getText(), (Integer) tf_peso_detotr.getValue()));
        Crear_mundo2.setVisible(false);
        mu.setNom_tortuga(tf_nom_tortuga.getText());
        mu.setPeso_tortu((Integer) tf_peso_detotr.getValue());
    }//GEN-LAST:event_enviar_mundoMouseClicked

    private void bt_crear_universoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crear_universoMouseClicked
        universo u = new universo();
        u.setCodigo_uni(tf_codigo_universo.getText());
        u.setEdad_uni((Integer) tf_edad_universo.getValue());
        c++;
        c_universo.setEnabled(false);
        Crear_mundo.dispose();
    }//GEN-LAST:event_bt_crear_universoMouseClicked

    private void jl_mundoDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_mundoDMouseClicked
        // TODO add your handling code here:
        //String raza, int energia, int max_anos, String region, int c_vivas, ArrayList<String> objetos, int peso_criaturas
        DefaultTreeModel m = (DefaultTreeModel) jt_arbol.getModel();//porque el ()
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        //DefaultMutableTreeNode nodo_mundo=new DefaultMutableTreeNode(new Criaturas(c.getRaza(),c.getEnergia(),c.getMax_anos(),c.getRegion(),c.getC_vivas(),c.getObjetos(),c.getPeso_criaturas()));
        nodo_mundo = new DefaultMutableTreeNode(new mundo_disco(mu.getNom_tortuga(), mu.getPeso_tortu()));
        raiz.add(nodo_mundo);
        model.clear();
        m.reload();
    }//GEN-LAST:event_jl_mundoDMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        /*
        Nombre de la raza.
•	Numero de energía.
•	Número máximo de años.
•	Nombre de la región.
•	Cantidad vivas de esa especie.
•	Lista de nombres de objetos mágicos propios de esas criaturas(puede estar vacía).
•	Peso criaturas

         */
        if (jl_criaturas.getSelectedIndex() >= 0) {
            String pos2 = JOptionPane.showInputDialog("Ingrese la posicion ");
            int pos = Integer.parseInt(pos2);

            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_arbol.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            modeloLISTA = (DefaultListModel) jl_criaturas.getModel();
            String raza;
            int energia;
            int anos;
            String region;
            int vivas;
            ArrayList<String> obj = new ArrayList();
            int peso;
            raza = ((Criaturas) modeloLISTA.get(jl_criaturas.getSelectedIndex())).getRaza();
            energia = ((Criaturas) modeloLISTA.get(jl_criaturas.getSelectedIndex())).getEnergia();
            anos = ((Criaturas) modeloLISTA.get(jl_criaturas.getSelectedIndex())).getMax_anos();
            region = ((Criaturas) modeloLISTA.get(jl_criaturas.getSelectedIndex())).getRegion();
            vivas = ((Criaturas) modeloLISTA.get(jl_criaturas.getSelectedIndex())).getC_vivas();
            obj = ((Criaturas) modeloLISTA.get(jl_criaturas.getSelectedIndex())).getObjetos();
            peso = ((Criaturas) modeloLISTA.get(jl_criaturas.getSelectedIndex())).getPeso_criaturas();

            for (int i = 0; i < raiz.getChildCount(); i++) {

                DefaultMutableTreeNode p = new DefaultMutableTreeNode(
                        new Criaturas(raza, energia, anos, region, vivas, obj, peso));
                ((DefaultMutableTreeNode) raiz.getChildAt(pos)).add(p);
            }
           
            modeloLISTA.clear();
            modeloARBOL.reload();

        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jl_mundoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_mundoMouseClicked
        if (evt.isMetaDown()) {
            popup_agregar_mundo.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jl_mundoMouseClicked

    private void agregar_mundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_mundoActionPerformed
        Crear_mundo2.setModal(true);//para solo poder a acceder a una ventana
        Crear_mundo2.pack();
        Crear_mundo2.setLocationRelativeTo(this);//centra con el frame principal
        Crear_mundo2.setVisible(true);
    }//GEN-LAST:event_agregar_mundoActionPerformed

    private void eliminar_mundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_mundoActionPerformed
        if (jl_mundo.getSelectedIndex() >= 0) {
            DefaultListModel mod = (DefaultListModel) jl_mundo.getModel();
            mod.remove(jl_mundo.getSelectedIndex());
        }
    }//GEN-LAST:event_eliminar_mundoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Crear_Criatura.setModal(true);//para solo poder a acceder a una ventana
        Crear_Criatura.pack();
        Crear_Criatura.setLocationRelativeTo(this);//centra con el frame principal
        Crear_Criatura.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jl_criaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_criaturasMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            popup_agregar_Criatura.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jl_criaturasMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (jl_criaturas.getSelectedIndex() >= 0) {
            DefaultListModel mod = (DefaultListModel) jl_criaturas.getModel();
            mod.remove(jl_criaturas.getSelectedIndex());
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void modificar_mundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_mundoActionPerformed
        String pos2 = JOptionPane.showInputDialog("Ingrese el nombre que desea modificar ");
        ((mundo_disco) model.get(jl_mundo.getSelectedIndex())).setNom_tortuga(pos2);
        String pos23 = JOptionPane.showInputDialog("Ingrese el peso que desea modificar ");
        int ent = Integer.parseInt(pos23);
        ((mundo_disco) model.get(jl_mundo.getSelectedIndex())).setPeso_tortu(ent);
    }//GEN-LAST:event_modificar_mundoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        String pos2 = JOptionPane.showInputDialog("Ingrese la raza que desea modificar ");
        String pos21 = JOptionPane.showInputDialog("Ingrese el energia que desea modificar ");
        String pos22 = JOptionPane.showInputDialog("Ingrese el maximo de anos que desea modificar ");
        String pos23 = JOptionPane.showInputDialog("Ingrese la region que desea modificar ");
        String pos24 = JOptionPane.showInputDialog("Ingrese la cantidad de criaturas vivas que desea modificar ");
        String pos25 = JOptionPane.showInputDialog("Ingrese el peso de las crituras que desea modificar ");
        int e1 = Integer.parseInt(pos21);
        int e2 = Integer.parseInt(pos22);
        int e3 = Integer.parseInt(pos24);
        int e4= Integer.parseInt(pos25);
        ((Criaturas) model.get(jl_criaturas.getSelectedIndex())).setRaza(pos2);
        ((Criaturas) model.get(jl_criaturas.getSelectedIndex())).setEnergia(e1);
        ((Criaturas) model.get(jl_criaturas.getSelectedIndex())).setMax_anos(e2);
        ((Criaturas) model.get(jl_criaturas.getSelectedIndex())).setRegion(pos23);
        ((Criaturas) model.get(jl_criaturas.getSelectedIndex())).setC_vivas(e3);
        ((Criaturas) model.get(jl_criaturas.getSelectedIndex())).setObjetos(listas);
        ((Criaturas) model.get(jl_criaturas.getSelectedIndex())).setPeso_criaturas(e4);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(princi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(princi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(princi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(princi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new princi2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Crear_Criatura;
    private javax.swing.JDialog Crear_mundo;
    private javax.swing.JDialog Crear_mundo2;
    private javax.swing.JMenuItem agregar_mundo;
    private javax.swing.JButton bt_crear_universo;
    private javax.swing.JButton bt_enviar;
    private javax.swing.JMenuItem c_criatura;
    private javax.swing.JMenuItem c_mundo;
    private javax.swing.JMenuItem c_universo;
    private javax.swing.JMenuItem eliminar_mundo;
    private javax.swing.JButton enviar_mundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> jl_criaturas;
    private javax.swing.JList<String> jl_mundo;
    private javax.swing.JButton jl_mundoD;
    private javax.swing.JTree jt_arbol;
    private javax.swing.JMenuItem modificar_mundo;
    private javax.swing.JPopupMenu popup_agregar_Criatura;
    private javax.swing.JPopupMenu popup_agregar_mundo;
    private javax.swing.JSpinner tf_anos;
    private javax.swing.JTextField tf_codigo_universo;
    private javax.swing.JSpinner tf_criaturasvivs;
    private javax.swing.JSpinner tf_edad_universo;
    private javax.swing.JSpinner tf_energia;
    private javax.swing.JTextField tf_nom_tortuga;
    private javax.swing.JTextField tf_objetos;
    private javax.swing.JSpinner tf_peso_detotr;
    private javax.swing.JSpinner tf_pesoc;
    private javax.swing.JTextField tf_raza;
    private javax.swing.JTextField tf_region;
    // End of variables declaration//GEN-END:variables
    //ArrayList<Criaturas> l_criaturas=new ArrayList();
    int c = 0;
    mundo_disco mu = new mundo_disco();
    DefaultListModel model;
    DefaultMutableTreeNode nodo_mundo;
    DefaultListModel modeloLISTA;
    int criaturas=0;
    int peso_cria=0;
    ArrayList<String> listas;
}
